services:
  - type: web
    name: chatgpt-relay-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SUPABASE_URL
        value: "https://hizcmicfsbirljnfaogr.supabase.co"
      - key: SUPABASE_KEY
        sync: false
        # Set to your Supabase service_role key (secret key)
      - key: API_KEY
        sync: false
      - key: RETENTION_HOURS
        value: "24"
    healthCheckPath: /health
    autoDeploy: true
